name: Run test suite
on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check
      - run: cargo clippy
      - run: cargo build
      - run: cargo test
      - run: cargo test --no-default-features
